name: WooPeople
description: An application for marketing by WooWain.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  animate_do: any
  cached_network_image: any
  cupertino_icons: any
  dio: any
  dropdown_button2: any
  firebase_auth: any
  firebase_core: any
  firebase_messaging: any
  flutter:
    sdk: flutter
  flutter_easyloading: any
  flutter_facebook_auth: any
  flutter_speed_dial: any
  flutter_svg: any
  fluttertoast: any
  font_awesome_flutter: any
  freezed: any
  freezed_annotation: any
  get: any
  google_sign_in: any
  image_cropper: any
  intl: any
  loading_animation_widget: any
  loading_indicator: any
  marquee: any
  pattern_formatter: any
  photo_view: any
  share_plus: any
  shared_preferences: any
  sign_in_with_apple: any
  url_launcher: any
  wechat_assets_picker: any

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  json_serializable: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
